baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "LoveIt"
[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'Why'
    url = '/why'
    weight = 20
  [[menus.main]]
    name = 'Test'
    url = '/test'
    weight = 30
